Base building
manuelfalonso/TowerDefense pull request #13
Opened 2024-05-21 16:08 UTC by Hollowriter

Added building spawners, building selector and cancel construction

2024-05-21 22:59 UTC, GonzaUlrich approved these changes

2024-05-24 01:32 UTC, Juli520 requested changes

2024-05-24 01:32 UTC, Juli520 commented on Tower Defense/Assets/JAM/Scripts/BaseBuilding/BuildingSelector.cs
> +            if (Input.GetKeyDown("1"))
Que las keys sean variables

2024-05-24 01:32 UTC, Juli520 commented on Tower Defense/Assets/JAM/Scripts/Managers/ObjectPool.cs.orig
> +using System.Collections;
Borrar este Script que es del conflicto

2024-05-24 01:32 UTC, Juli520 commented on Tower Defense/Assets/JAM/Scripts/Managers/ObjectPool.cs
>  namespace JAM
Agregar namespace

2024-05-24 01:32 UTC, Juli520 commented on Tower Defense/Assets/JAM/Scripts/Managers/ObjectPool.cs
> +        [SerializeField] private BuildingType _buildingType;
Separar lógica del pool base con la de edificios y otras cosas que lleguen a usar pool (Clase hija)

2024-05-24 01:32 UTC, Juli520 commented on Tower Defense/Assets/JAM/Scripts/BaseBuilding/BuildingSpawner.cs
> +        {
agregarle el "base.Awake()" porque sino no funciona el Singleton

2024-05-27 19:11 UTC, Juli520 approved these changes

2024-05-27 19:11 UTC, merged