Base test tower readded
manuelfalonso/TowerDefense pull request #4
Opened 2024-04-30 18:31 UTC by Hollowriter

Added a base tower that outputs logs when adds an enemy to the list, removes it and calls the shoot function. (Pending to create the bullet)

2024-05-07 13:34 UTC, manuelfalonso requested changes
:)

2024-05-07 13:34 UTC, manuelfalonso commented on Tower Defense/Assets/JAM/Scripts/Towers/BaseTower.cs
> +namespace JAM
Agregar namespace

2024-05-07 17:10 UTC, Hollowriter commented on Tower Defense/Assets/JAM/Scripts/Towers/BaseTower.cs
> +namespace JAM
Ahi esta, agregado

2024-05-09 01:05 UTC, Juli520 commented
@Hollowriter en el otro commit están los mismos Scripts que en este, ¿le damos bola al otro y este lo cerramos?

2024-05-09 01:08 UTC, Hollowriter commented
> @Hollowriter en el otro commit están los mismos Scripts que en este, ¿le damos bola al otro y este lo cerramos?

Si, mejor este cierrenlo, ahi me pongo a ver los comentarios del otro

2024-05-09 01:13 UTC, closed without merging